# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10bd8d2e80b68381c55ed78f0e55d5948fe9f61fb2f3d3c8b4f6da82b4c95cb679934675415c40a31a8f08f020fa8a0dcfece93f46994ed013cf3e481947f518

test:
  secret_key_base: e87050b5dcaef54e2b019e1db4c4bc697b200283765b0a11407bc7ecd884e7ebefb93a860a815c7396f8edca83e1f6a150172bfef70d8a5b54b35db0ae0680f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
